# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kurl < Formula
  desc "A fast, colorized Go CLI for viewing HTTP API responses in a clean, human-readable format."
  homepage "https://github.com/kavix/kurl"
  version "0.1.0-auto.2026.8.10-082554-ab90f0b"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kavix/kurl/releases/download/v0.1.0-auto.2026.8.10-082554-ab90f0b/kurl_darwin_amd64.tar.gz"
      sha256 "d6d64c6dac81c94a16d6d5c9ab1d45e1db1481dd2b2bc1556b2ba0e70f925acb"

      define_method(:install) do
        bin.install "kurl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kavix/kurl/releases/download/v0.1.0-auto.2026.8.10-082554-ab90f0b/kurl_darwin_arm64.tar.gz"
      sha256 "8ad4e42eb6e6b1c594d0f7542dfb9e2ff14732aca2194b1b8af409f3d7641868"

      define_method(:install) do
        bin.install "kurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kavix/kurl/releases/download/v0.1.0-auto.2026.8.10-082554-ab90f0b/kurl_linux_amd64.tar.gz"
      sha256 "48feeb988aed59d4a74d9618b0fafa9852c040ed924ac03cb3a5adababa83698"
      define_method(:install) do
        bin.install "kurl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kavix/kurl/releases/download/v0.1.0-auto.2026.8.10-082554-ab90f0b/kurl_linux_arm64.tar.gz"
      sha256 "56d0902eb0d2fbbf1d9cd0a9627996ccda89cfb3ce674a87bc725aa0c83e5134"
      define_method(:install) do
        bin.install "kurl"
      end
    end
  end
end
