# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kurl < Formula
  desc "A fast, colorized Go CLI for viewing HTTP API responses in a clean, human-readable format."
  homepage "https://github.com/kavix/kurl"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kavix/kurl/releases/download/v1.0.1/kurl_darwin_amd64.tar.gz"
      sha256 "3d6abd595aef2c38a978584b9dbb37bcba761a5a3553b102c73b0baa0bf064ed"

      define_method(:install) do
        bin.install "kurl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kavix/kurl/releases/download/v1.0.1/kurl_darwin_arm64.tar.gz"
      sha256 "a2ef96510a5c42089017912259a9b89fa2502b560c791561549cb89769d073e7"

      define_method(:install) do
        bin.install "kurl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/kavix/kurl/releases/download/v1.0.1/kurl_linux_amd64.tar.gz"
      sha256 "a81cffbc29d59bc23a56ca3aa4be0730cb57959583b05f483497ea989b5de4a6"
      define_method(:install) do
        bin.install "kurl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kavix/kurl/releases/download/v1.0.1/kurl_linux_arm64.tar.gz"
      sha256 "1db8ca44f5c2014343a223dc3acf03eef7bb16484b5a95ee1c98978494730e1f"
      define_method(:install) do
        bin.install "kurl"
      end
    end
  end
end
